// Module2_FrontendDev/Trivikraman/handson_05/student-portal-react/src/components/CourseCard.jsx
import React from 'react';

export default function CourseCard(props) {
  const { id, name, code, credits, grade, isEnrolled, onEnroll } = props;
  
  return (
    <article className={`course-card ${isEnrolled ? 'enrolled' : ''}`}>
      <div className="card-tag">{credits >= 4 ? 'Core' : 'Elective'}</div>
      <h3>{name}</h3>
      <p className="course-desc">This is a React-managed course component for {name} ({code}).</p>
      <div className="card-footer">
        <span className="course-code">{code}</span>
        <span className="course-credits">{credits} Credits</span>
        {isEnrolled ? (
          <button className="btn-card btn-enrolled" disabled>Enrolled</button>
        ) : (
          <button className="btn-card btn-enroll" onClick={() => onEnroll(id)}>Enroll</button>
        )}
      </div>
    </article>
  );
}

// Module2_FrontendDev/Trivikraman/handson_07/student-portal-angular/src/app/course-card/course-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-course-card',
  templateUrl: './course-card.component.html',
  styleUrls: []
})
export class CourseCardComponent {
  
  // Step 92: Declare Input properties
  @Input() name: string = '';
  @Input() code: string = '';
  @Input() credits: number = 0;
  @Input() grade: string = '';
}

<article class="course-card">
  <div class="card-tag">{{ credits >= 4 ? 'Core' : 'Elective' }}</div>
  <h3>{{ name }}</h3>
  <p class="course-desc">This is an Angular component for {{ name }} ({{ code }}).</p>
  <div class="card-footer">
    <span class="course-code">{{ code }}</span>
    <span class="course-credits">{{ credits }} Credits</span>
  </div>
</article>
