// Module2_FrontendDev/Trivikraman/handson_06/student-portal-react/src/components/Header.jsx
import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useSelector } from 'react-redux';

export default function Header(props) {
  const { siteName = "Student Portal" } = props;
  const location = useLocation();
  
  // Consume global state count via Redux selector (Step 83 & 89)
  const enrolledCourses = useSelector(state => state.enrollment.enrolledCourses);
  const enrolledCount = enrolledCourses.length;

  const isActive = (path) => location.pathname === path;

  return (
    <header>
      <div className="logo">
        <Link to="/" style={{ textDecoration: 'none', color: 'inherit' }}>
          <span className="logo-accent">{siteName.split(' ')[0]}</span> {siteName.split(' ').slice(1).join(' ')}
        </Link>
      </div>
      <nav>
        <ul>
          <li>
            <Link to="/" className={isActive('/') ? 'active' : ''}>Home</Link>
          </li>
          <li>
            <Link to="/courses" className={isActive('/courses') || location.pathname.startsWith('/courses/') ? 'active' : ''}>
              Courses
              {enrolledCount > 0 && (
                <span className="enrolled-badge">{enrolledCount}</span> // (Step 83)
              )}
            </Link>
          </li>
          <li>
            <Link to="/profile" className={isActive('/profile') ? 'active' : ''}>Profile</Link>
          </li>
        </ul>
      </nav>
    </header>
  );
}

// Module2_FrontendDev/Trivikraman/handson_08/student-portal-vue/src/components/Header.vue
<script setup>
import { useEnrollmentStore } from '../stores/enrollment';

// Step 120: Display count using store.enrolledCourses.length
const store = useEnrollmentStore();
</script>

<template>
  <header>
    <div class="logo">
      <router-link to="/" style="text-decoration: none; color: inherit;">
        <span class="logo-accent">Student</span>Portal
      </router-link>
    </div>
    <nav>
      <ul>
        <li>
          <router-link to="/" exact-active-class="active">Home</router-link>
        </li>
        <li>
          <router-link to="/courses" active-class="active">
            Courses
            <!-- Step 120: Reactive store length count -->
            <span v-if="store.enrolledCourses.length > 0" class="enrolled-badge">
              {{ store.enrolledCourses.length }}
            </span>
          </router-link>
        </li>
        <li>
          <router-link to="/profile" active-class="active">Profile</router-link>
        </li>
      </ul>
    </nav>
  </header>
</template>

<style scoped>
/* Relying on global stylesheet rules */
</style>
