// Module2_FrontendDev/Trivikraman/handson_05/student-portal-react/src/components/Header.jsx
import React from 'react';

export default function Header(props) {
  const { siteName, enrolledCount } = props;
  
  return (
    <header>
      <div className="logo">
        <span class="logo-accent">{siteName.split(' ')[0]}</span> {siteName.split(' ').slice(1).join(' ')}
      </div>
      <nav>
        <ul>
          <li><a href="#" className="active">Home</a></li>
          <li>
            <a href="#">
              Courses
              {enrolledCount > 0 && (
                <span className="enrolled-badge">{enrolledCount}</span>
              )}
            </a>
          </li>
          <li><a href="#">Profile</a></li>
        </ul>
      </nav>
    </header>
  );
}

// Module2_FrontendDev/Trivikraman/handson_07/student-portal-angular/src/app/header/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: []
})
export class HeaderComponent {
  siteName = 'Student Portal';
}

<header>
  <div class="logo">
    <span class="logo-accent">Student</span>Portal
  </div>
  <nav>
    <ul>
      <li>
        <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">Home</a>
      </li>
      <li>
        <a [routerLink]="['/profile']" routerLinkActive="active">Profile</a>
      </li>
    </ul>
  </nav>
</header>
